# Generated by Django 5.2.17 on 2026-09-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('finish_location', models.CharField(max_length=255)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('finish_latitude', models.FloatField()),
                ('finish_longitude', models.FloatField()),
                ('total_distance_miles', models.FloatField()),
                ('total_duration_minutes', models.FloatField()),
                ('total_gallons', models.FloatField()),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stops_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route Query Log',
                'verbose_name_plural': 'Route Query Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
